export const RECS = {
  pageSize: 3
};

export const PAGINATION = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT'
}

export const RATING = [
  { value: 'awesome', label: 'awesome' }, 
  { value: 'very good', label: 'very good' }, 
  { value: 'good', label: 'good' }, 
  { value: 'average', label: 'average' }, 
  { value: 'poor', label: 'poor' } 
];

export const GENRES = [
  { value: 'aggrotech', label: 'aggrotech' },
  { value: 'alternative metal', label: 'alternative metal' },
  { value: 'alternative rock', label: 'alternative rock' },
  { value: 'beatdown', label: 'beatdown' },
  { value: 'black metal', label: 'black metal' },
  { value: 'blackened crust', label: 'blackened crust' },
  { value: 'blackened death metal', label: 'blackened death metal' },
  { value: 'blackgaze', label: 'blackgaze' },
  { value: 'brutal death metal', label: 'brutal death metal' },
  { value: 'crossover thrash', label: 'crossover thrash' },
  { value: 'dark electro', label: 'dark electro' },
  { value: 'death metal', label: 'death metal' },
  { value: 'deathcore', label: 'deathcore' },
  { value: 'deathgrind', label: 'deathgrind' },
  { value: 'djent', label: 'djent' },
  { value: 'doom metal', label: 'doom metal' },
  { value: 'drum n bass', label: 'drum n bass' },
  { value: 'dubstep', label: 'dubstep' },
  { value: 'electro', label: 'electro' },
  { value: 'electronicore', label: 'electronicore' },
  { value: 'electronic rock', label: 'electronic rock' },
  { value: 'EBM', label: 'EBM' },
  { value: 'experimental metal', label: 'experimental metal' },
  { value: 'experimental rock', label: 'experimental rock' },
  { value: 'folk metal', label: 'folk metal' },
  { value: 'funk metal', label: 'funk metal' },
  { value: 'glam metal', label: 'glam metal' },
  { value: 'goa trance', label: 'goa trance' },
  { value: 'goregrind', label: 'goregrind' },
  { value: 'gothic metal', label: 'gothic metal' },
  { value: 'grindcore', label: 'grindcore' },
  { value: 'groove metal', label: 'groove metal' },
  { value: 'hard rock', label: 'hard rock' },
  { value: 'hardcore', label: 'hardcore' },
  { value: 'heavy metal', label: 'heavy metal' },
  { value: 'industrial black metal', label: 'industrial black metal' },
  { value: 'industrial death metal', label: 'industrial death metal' },
  { value: 'industrial metal', label: 'industrial metal' },
  { value: 'industrial rock', label: 'industrial rock' },
  { value: 'instrumental', label: 'instrumental' },
  { value: 'melodic death metal', label: 'melodic death metal' },
  { value: 'melodic metalcore', label: 'melodic metalcore' },
  { value: 'metalcore', label: 'metalcore' },
  { value: 'modern metal', label: 'modern metal' },
  { value: 'modern rock', label: 'modern rock' },
  { value: 'nu metal', label: 'nu metal' },
  { value: 'other', label: 'other' },
  { value: 'pagan metal', label: 'pagan metal' },
  { value: 'post metal', label: 'post metal' },
  { value: 'post rock', label: 'post rock' },
  { value: 'post-black metal', label: 'post-black metal' },
  { value: 'post-hardcore', label: 'post-hardcore' },
  { value: 'power metal', label: 'power metal' },
  { value: 'progressive metal', label: 'progressive metal' },
  { value: 'progressive deathcore', label: 'progressive deathcore' },
  { value: 'progressive metalcore', label: 'progressive metalcore' },
  { value: 'progressive rock', label: 'progressive rock' },
  { value: 'psytrance', label: 'psytrance' },
  { value: 'rap metal', label: 'rap metal' },
  { value: 'rapcore', label: 'rapcore' },
  { value: 'sludge metal', label: 'sludge metal' },
  { value: 'space metal', label: 'space metal' },
  { value: 'stoner metal', label: 'stoner metal' },
  { value: 'symphonic black metal', label: 'symphonic black metal' },
  { value: 'symphonic death metal', label: 'symphonic death metal' },
  { value: 'symphonic metal', label: 'symphonic metal' },
  { value: 'technical death metal', label: 'technical death metal' },
  { value: 'technical deathcore', label: 'technical deathcore' },
  { value: 'thrash metal', label: 'thrash metal' },
  { value: 'trance', label: 'trance' },
  { value: 'viking metal', label: 'viking metal' }
]
