export const TYPES = ['band', 'album', 'track'];

export const RATING = [
  { value: 'awesome', label: 'awesome' }, 
  { value: 'very good', label: 'very good' }, 
  { value: 'good', label: 'good' }, 
  { value: 'average', label: 'average' }, 
  { value: 'poor', label: 'poor' } 
];

export const GENRES = [
  { value: 'metalcore', label: 'metalcore' },
  { value: 'deathcore', label: 'deathcore' },
  { value: 'grindcore', label: 'grindcore' },
  { value: 'hardcore', label: 'hardcore' },
  { value: 'rapcore', label: 'rapcore' },
  { value: 'post-hardcore', label: 'post-hardcore' },
  { value: 'beatdown', label: 'beatdown' },
  { value: 'death metal', label: 'death metal' },
  { value: 'deathgrind', label: 'deathgrind' },
  { value: 'melodic death metal', label: 'melodic death metal' },
  { value: 'technical death metal', label: 'technical death metal' },
  { value: 'brutal death metal', label: 'brutal death metal' },
  { value: 'blackened death metal', label: 'blackened death metal' },
  { value: 'black metal', label: 'black metal' },
  { value: 'post-black metal', label: 'post-black metal' },
  { value: 'pagan metal', label: 'pagan metal' },
  { value: 'viking metal', label: 'viking metal' },
  { value: 'sludge', label: 'sludge' },
  { value: 'doom metal', label: 'doom metal' },
  { value: 'djent', label: 'djent' },
  { value: 'progressive metal', label: 'progressive metal' },
  { value: 'post metal', label: 'post metal' },
  { value: 'groove metal', label: 'groove metal' },
  { value: 'alternative metal', label: 'alternative metal' },
  { value: 'gothic metal', label: 'gothic metal' },
  { value: 'thrash metal', label: 'thrash metal' },
  { value: 'industrial metal', label: 'industrial metal' },
  { value: 'modern metal', label: 'modern metal' },
  { value: 'nu metal', label: 'nu metal' },
  { value: 'power metal', label: 'power metal' },
  { value: 'heavy metal', label: 'heavy metal' },
  { value: 'experimental metal', label: 'experimental metal' },
  { value: 'symphonic metal', label: 'symphonic metal' },
  { value: 'folk metal', label: 'folk metal' },
  { value: 'stoner', label: 'stoner' },
  { value: 'instrumental', label: 'instrumental' },
  { value: 'alternative rock', label: 'alternative rock' },
  { value: 'post rock', label: 'post rock' },
  { value: 'modern rock', label: 'modern rock' },
  { value: 'progressive rock', label: 'progressive rock' },
  { value: 'industrial rock', label: 'industrial rock' },
  { value: 'hard rock', label: 'hard rock' },
  { value: 'experimental rock', label: 'experimental rock' },
  { value: 'aggrotech', label: 'aggrotech' },
  { value: 'psytrance', label: 'psytrance' },
  { value: 'aggrotech', label: 'aggrotech' },
  { value: 'electronic', label: 'electronic' },
  { value: 'EBM', label: 'EBM' },
  { value: 'dark electro', label: 'dark electro' },
  { value: 'trance', label: 'trance' },
  { value: 'dubstep', label: 'dubstep' },
  { value: 'drum n bass', label: 'drum n bass' },
  { value: 'goa trance', label: 'goa trance' },
  { value: 'other', label: 'other' }
]
